VERSION_SALT: "snoopy"
STORAGE_PATH: "/home/ericlee/EOSS/data"
METADATA_DB_PATH: "/home/ericlee/EOSS/mds/mds.sql"
LOGGING_PATH: "/home/ericlee/EOSS/log"
LOG_BACKUP_COUNT: 10
LOG_MAX_BYTES: 1073741824
SAFEMODE: False
